-- RNSP (Rwanda National Sports Platform) 
-- Full Database Schema for PostgreSQL / Supabase
-- Generated: 2026-05-24

-- 1. CREATE ENUMS
CREATE TYPE "Role" AS ENUM ('SUPERADMIN', 'LEAGUE_ADMIN', 'TEAM_MANAGER', 'PUBLIC');
CREATE TYPE "SportCategory" AS ENUM ('FIELD', 'COURT', 'TRACK', 'WATER', 'COMBAT', 'RACKET', 'OTHER');
CREATE TYPE "Gender" AS ENUM ('MALE', 'FEMALE', 'MIXED', 'DISABLED');
CREATE TYPE "AgeCategory" AS ENUM ('SENIOR', 'U20', 'U17', 'U15', 'U13', 'JUNIOR', 'VETERAN', 'ALL');
CREATE TYPE "CompLevel" AS ENUM ('NATIONAL', 'REGIONAL', 'DISTRICT', 'SCHOOL');
CREATE TYPE "LeagueFormat" AS ENUM ('LEAGUE', 'KNOCKOUT', 'GROUP_KNOCKOUT', 'ROUND_ROBIN');
CREATE TYPE "LeagueStatus" AS ENUM ('UPCOMING', 'ACTIVE', 'COMPLETED', 'SUSPENDED');
CREATE TYPE "TeamStatus" AS ENUM ('PENDING', 'VERIFIED', 'SUSPENDED', 'REJECTED');
CREATE TYPE "PlayerSkill" AS ENUM ('ELITE', 'PROFESSIONAL', 'SEMI_PROFESSIONAL', 'AMATEUR');
CREATE TYPE "PlayerGender" AS ENUM ('MALE', 'FEMALE');
CREATE TYPE "PlayerStatus" AS ENUM ('PENDING', 'VERIFIED', 'SUSPENDED', 'REJECTED');
CREATE TYPE "DocType" AS ENUM ('BIRTH_CERTIFICATE', 'PASSPORT', 'NATIONAL_ID', 'MEDICAL', 'OTHER');
CREATE TYPE "DocStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED');
CREATE TYPE "RoundType" AS ENUM ('GROUP', 'KNOCKOUT', 'FINAL', 'SEMI_FINAL', 'QUARTER_FINAL', 'REGULAR');
CREATE TYPE "FixtureStatus" AS ENUM ('SCHEDULED', 'LIVE', 'COMPLETED', 'POSTPONED', 'CANCELLED');
CREATE TYPE "EventType" AS ENUM ('GOAL', 'OWN_GOAL', 'PENALTY', 'RED_CARD', 'YELLOW_CARD', 'SUBSTITUTION', 'INJURY', 'VAR', 'KICKOFF', 'HALFTIME', 'FULLTIME', 'EXTRA_TIME');
CREATE TYPE "TransferType" AS ENUM ('PERMANENT', 'LOAN', 'FREE', 'RETURN_FROM_LOAN');
CREATE TYPE "RegStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED');
CREATE TYPE "NewsCategory" AS ENUM ('NEWS', 'ANNOUNCEMENT', 'RESULT', 'TRANSFER', 'INJURY', 'OTHER');
CREATE TYPE "ContactStatus" AS ENUM ('NEW', 'READ', 'REPLIED');
CREATE TYPE "SchoolCategory" AS ENUM ('SECONDARY', 'TVET', 'PRIMARY');
CREATE TYPE "AkcGender" AS ENUM ('MALE', 'FEMALE', 'MIXED', 'INCLUSIVE');
CREATE TYPE "AkcAgeCategory" AS ENUM ('U13', 'U15', 'U17', 'U20', 'OPEN');
CREATE TYPE "AkcLevel" AS ENUM ('CELL', 'SECTOR', 'DISTRICT', 'PROVINCE', 'NATIONAL');
CREATE TYPE "AkcIdType" AS ENUM ('NATIONAL_ID', 'BIRTH_CERT', 'PASSPORT');
CREATE TYPE "AkcCompStatus" AS ENUM ('UPCOMING', 'ONGOING', 'COMPLETED', 'CANCELLED');
CREATE TYPE "AkcStage" AS ENUM ('GROUP', 'ROUND16', 'QUARTERFINAL', 'SEMIFINAL', 'FINAL', 'THIRD_PLACE');
CREATE TYPE "AkcFixtureStatus" AS ENUM ('SCHEDULED', 'ONGOING', 'COMPLETED', 'POSTPONED', 'CANCELLED');
CREATE TYPE "AkcAnnouncementCategory" AS ENUM ('GENERAL', 'REGISTRATION', 'COMPETITION', 'RESULTS', 'URGENT');

-- 2. CREATE TABLES
CREATE TABLE "Setting" (
    "id" SERIAL NOT NULL,
    "skey" VARCHAR(100) NOT NULL,
    "sval" TEXT,
    "label" VARCHAR(200),
    "grp" VARCHAR(80) NOT NULL DEFAULT 'general',
    CONSTRAINT "Setting_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "User" (
    "id" SERIAL NOT NULL,
    "username" VARCHAR(80) NOT NULL,
    "password" VARCHAR(255) NOT NULL,
    "fullName" VARCHAR(200) NOT NULL,
    "email" VARCHAR(200),
    "phone" VARCHAR(50),
    "role" "Role" NOT NULL DEFAULT 'PUBLIC',
    "active" BOOLEAN NOT NULL DEFAULT true,
    "verified" BOOLEAN NOT NULL DEFAULT false,
    "avatar" VARCHAR(300),
    "lastLogin" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "RefreshToken" (
    "id" SERIAL NOT NULL,
    "token" VARCHAR(512) NOT NULL,
    "userId" INTEGER NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "RefreshToken_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Sport" (
    "id" SERIAL NOT NULL,
    "name" VARCHAR(150) NOT NULL,
    "slug" VARCHAR(170),
    "icon" VARCHAR(10) NOT NULL DEFAULT '🏅',
    "description" TEXT,
    "coverImage" VARCHAR(300),
    "category" "SportCategory" NOT NULL DEFAULT 'OTHER',
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,