-- CreateEnum
CREATE TYPE "UmugandaStatus" AS ENUM ('EXPECTED', 'CONFIRMED', 'MOVED', 'DISABLED');

-- CreateEnum
CREATE TYPE "UmugandaSource" AS ENUM ('GENERATED', 'ADMIN');

-- CreateEnum
CREATE TYPE "UmugandaDecision" AS ENUM ('CONTINUE', 'MOVED', 'AFTER_UMUGANDA', 'AFFECTED');

-- CreateEnum
CREATE TYPE "UmugandaNoticeKind" AS ENUM ('GENERAL', 'CONTINUE', 'RESCHEDULED', 'AFTER_UMUGANDA', 'AFFECTED');

-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "FixtureStatus" ADD VALUE 'CONFIRMED';
ALTER TYPE "FixtureStatus" ADD VALUE 'UMUGANDA_CONFLICT';
ALTER TYPE "FixtureStatus" ADD VALUE 'RESCHEDULED';

-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "AkcFixtureStatus" ADD VALUE 'CONFIRMED';
ALTER TYPE "AkcFixtureStatus" ADD VALUE 'UMUGANDA_CONFLICT';
ALTER TYPE "AkcFixtureStatus" ADD VALUE 'RESCHEDULED';

-- AlterTable
ALTER TABLE "Fixture" ADD COLUMN     "originalMatchDate" TIMESTAMP(3),
ADD COLUMN     "rescheduleReason" VARCHAR(500),
ADD COLUMN     "umugandaDayId" INTEGER,
ADD COLUMN     "umugandaDecision" "UmugandaDecision";

-- AlterTable
ALTER TABLE "AkcFixture" ADD COLUMN     "originalMatchDate" TIMESTAMP(3),
ADD COLUMN     "rescheduleReason" VARCHAR(500),
ADD COLUMN     "umugandaDayId" INTEGER,
ADD COLUMN     "umugandaDecision" "UmugandaDecision";

-- CreateTable
CREATE TABLE "UmugandaDay" (
    "id" SERIAL NOT NULL,
    "date" DATE NOT NULL,
    "month" SMALLINT NOT NULL,
    "year" SMALLINT NOT NULL,
    "title" VARCHAR(200),
    "description" TEXT,
    "status" "UmugandaStatus" NOT NULL DEFAULT 'EXPECTED',
    "source" "UmugandaSource" NOT NULL DEFAULT 'GENERATED',
    "autoGenerated" BOOLEAN NOT NULL DEFAULT true,
    "overridden" BOOLEAN NOT NULL DEFAULT false,
    "startTime" VARCHAR(5) NOT NULL DEFAULT '08:00',
    "endTime" VARCHAR(5) NOT NULL DEFAULT '11:00',
    "createdById" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "UmugandaDay_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "UmugandaNotice" (
    "id" SERIAL NOT NULL,
    "umugandaDayId" INTEGER NOT NULL,
    "fixtureId" INTEGER,
    "akcFixtureId" INTEGER,
    "kind" "UmugandaNoticeKind" NOT NULL DEFAULT 'GENERAL',
    "title" VARCHAR(300) NOT NULL,
    "body" TEXT NOT NULL,
    "originalDate" TIMESTAMP(3),
    "newDate" TIMESTAMP(3),
    "reason" VARCHAR(500),
    "published" BOOLEAN NOT NULL DEFAULT true,
    "dedupeKey" VARCHAR(200) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "UmugandaNotice_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "UmugandaDay_year_month_idx" ON "UmugandaDay"("year", "month");

-- CreateIndex
CREATE INDEX "UmugandaDay_status_idx" ON "UmugandaDay"("status");

-- CreateIndex
CREATE UNIQUE INDEX "UmugandaDay_date_key" ON "UmugandaDay"("date");

-- CreateIndex
CREATE UNIQUE INDEX "UmugandaNotice_dedupeKey_key" ON "UmugandaNotice"("dedupeKey");

-- CreateIndex
CREATE INDEX "UmugandaNotice_umugandaDayId_idx" ON "UmugandaNotice"("umugandaDayId");

-- CreateIndex
CREATE INDEX "UmugandaNotice_published_createdAt_idx" ON "UmugandaNotice"("published", "createdAt");

-- CreateIndex
CREATE INDEX "Fixture_umugandaDayId_idx" ON "Fixture"("umugandaDayId");

-- CreateIndex
CREATE INDEX "Fixture_matchDate_idx" ON "Fixture"("matchDate");

-- CreateIndex
CREATE INDEX "AkcFixture_umugandaDayId_idx" ON "AkcFixture"("umugandaDayId");

-- CreateIndex
CREATE INDEX "AkcFixture_matchDate_idx" ON "AkcFixture"("matchDate");

-- AddForeignKey
ALTER TABLE "Fixture" ADD CONSTRAINT "Fixture_umugandaDayId_fkey" FOREIGN KEY ("umugandaDayId") REFERENCES "UmugandaDay"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AkcFixture" ADD CONSTRAINT "AkcFixture_umugandaDayId_fkey" FOREIGN KEY ("umugandaDayId") REFERENCES "UmugandaDay"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UmugandaDay" ADD CONSTRAINT "UmugandaDay_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UmugandaNotice" ADD CONSTRAINT "UmugandaNotice_umugandaDayId_fkey" FOREIGN KEY ("umugandaDayId") REFERENCES "UmugandaDay"("id") ON DELETE CASCADE ON UPDATE CASCADE;

