/**
 * Umuganda service — database side of the community-work calendar.
 *
 * Two rules drive everything here:
 *
 *   1. The last Saturday is an EXPECTED date, never an official one. Generated
 *      rows carry status EXPECTED; only an administrator promotes one to
 *      CONFIRMED, MOVED or DISABLED.
 *   2. The administrator's decision always beats the calculation. Generation is
 *      idempotent and NEVER overwrites a row a human has touched (`overridden`).
 *
 * The system flags clashes and offers options. It never cancels a match.
 */

const prisma = require('../config/db');
const {
  lastSaturdayOf,
  monthsFrom,
  dayKey,
  kigaliDayKey,
  clashesWithWindow,
} = require('./umuganda.logic');

const DEFAULT_MONTHS_AHEAD = 12;

/**
 * Ensure a generated Umuganda row exists for each of the next `count` months.
 * Safe to call repeatedly — that is the point, it runs on boot and on demand.
 *
 * A row an administrator has overridden is left completely alone.
 */
const ensureUpcomingMonths = async (count = DEFAULT_MONTHS_AHEAD, from = new Date()) => {
  const created: any[] = [];

  for (const { year, month } of monthsFrom(from, count)) {
    // An override for this month may sit on a different DAY than the computed
    // one (that is what MOVED means), so look the month up by year+month rather
    // than by the calculated date.
    const existingForMonth = await prisma.umugandaDay.findFirst({
      where: { year, month },
    });
    if (existingForMonth) continue;

    const date = lastSaturdayOf(year, month);
    try {
      const row = await prisma.umugandaDay.create({
        data: {
          date,
          month,
          year,
          status: 'EXPECTED',
          source: 'GENERATED',
          autoGenerated: true,
          overridden: false,
        },
      });
      created.push(row);
    } catch (error: any) {
      // P2002 = another request generated the same day first. Benign.
      if (error?.code !== 'P2002') throw error;
    }
  }

  return created;
};

/** Umuganda days that actually count — DISABLED ones are excluded. */
const getEffectiveDays = async (from: Date, to: Date) =>
  prisma.umugandaDay.findMany({
    where: {
      date: { gte: from, lte: to },
      status: { not: 'DISABLED' },
    },
    orderBy: { date: 'asc' },
  });

/** The next Umuganda on or after `from`, or null if none is generated yet. */
const getNextDay = async (from = new Date()) => {
  const midnight = new Date(Date.UTC(from.getUTCFullYear(), from.getUTCMonth(), from.getUTCDate()));
  return prisma.umugandaDay.findFirst({
    where: { date: { gte: midnight }, status: { not: 'DISABLED' } },
    orderBy: { date: 'asc' },
  });
};

/**
 * Does `matchDate` land on an Umuganda day?
 *
 * Returns null when clear, otherwise the day plus whether the kickoff actually
 * overlaps the community-work window. Sharing the date is worth telling the
 * admin about; overlapping the window is the hard clash.
 */
const detectConflict = async (matchDate: Date | string | null | undefined) => {
  if (!matchDate) return null;
  const d = matchDate instanceof Date ? matchDate : new Date(matchDate);
  if (Number.isNaN(d.getTime())) return null;

  const key = kigaliDayKey(d);
  if (!key) return null;

  // Kigali is UTC+2, so a single Kigali day can straddle two UTC days. Fetch the
  // three-day window around it and match on the day key rather than trusting a
  // raw range comparison against a DATE column.
  const centre = new Date(key + 'T00:00:00.000Z');
  const from = new Date(centre.getTime() - 86400000);
  const to = new Date(centre.getTime() + 86400000);

  const candidates = await getEffectiveDays(from, to);
  const day = candidates.find((u: any) => dayKey(u.date) === key);
  if (!day) return null;

  return {
    umugandaDay: day,
    overlapsWindow: clashesWithWindow(d, day.startTime, day.endTime),
  };
};

/**
 * Raise a public notice, at most once per (day, fixture, kind, target date).
 *
 * The dedupe key carries the new date, so a genuine SECOND reschedule of the
 * same match still notifies — but re-saving the same decision does not.
 */
const raiseNotice = async ({
  umugandaDayId,
  fixtureId = null,
  akcFixtureId = null,
  kind = 'GENERAL',
  title,
  body,
  originalDate = null,
  newDate = null,
  reason = null,
}: any) => {
  const target = newDate ? new Date(newDate).toISOString() : 'none';
  const dedupeKey = [
    umugandaDayId,
    fixtureId ? 'f' + fixtureId : akcFixtureId ? 'a' + akcFixtureId : 'general',
    kind,
    target,
  ].join(':').slice(0, 200);

  try {
    return await prisma.umugandaNotice.create({
      data: {
        umugandaDayId,
        fixtureId,
        akcFixtureId,
        kind,
        title,
        body,
        originalDate,
        newDate,
        reason,
        dedupeKey,
      },
    });
  } catch (error: any) {
    // P2002 on dedupeKey — this exact notice already exists. That is success.
    if (error?.code === 'P2002') {
      return prisma.umugandaNotice.findUnique({ where: { dedupeKey } });
    }
    throw error;
  }
};

/** Notices for the public feed, newest first. */
const getPublishedNotices = async (limit = 20) =>
  prisma.umugandaNotice.findMany({
    where: { published: true },
    orderBy: { createdAt: 'desc' },
    take: limit,
    include: { umugandaDay: true },
  });

/**
 * An AkcTeam has no `name` of its own — a school fields several teams and they
 * are told apart by gender and age category (the convention the Amashuri admin
 * screens already use). The Umuganda components are shared across both fixture
 * families, so give the AKC side the same `name` field the League side has
 * rather than teaching every component about two shapes.
 */
const akcTeamName = (team: any) => {
  if (!team) return null;
  const school = team.school?.name || team.school?.shortName;
  if (!school) return null;
  const qualifier = [team.gender, team.ageCategory].filter(Boolean).join(' ');
  return qualifier ? `${school} ${qualifier}` : school;
};

const withAkcTeamNames = (fixture: any) => ({
  ...fixture,
  homeTeam: fixture.homeTeam && { ...fixture.homeTeam, name: akcTeamName(fixture.homeTeam) },
  awayTeam: fixture.awayTeam && { ...fixture.awayTeam, name: akcTeamName(fixture.awayTeam) },
});

/** Both fixture families that fall on a given Umuganda day. */
const getAffectedFixtures = async (umugandaDay: any) => {
  const key = dayKey(umugandaDay.date);
  const centre = new Date(key + 'T00:00:00.000Z');
  // Widen by a day either side, then filter by Kigali day key.
  const from = new Date(centre.getTime() - 86400000);
  const to = new Date(centre.getTime() + 2 * 86400000);

  const [fixtures, akcFixtures] = await Promise.all([
    prisma.fixture.findMany({
      where: {
        OR: [
          { matchDate: { gte: from, lte: to } },
          { umugandaDayId: umugandaDay.id },
        ],
      },
      include: {
        homeTeam: { select: { id: true, name: true, shortName: true, logo: true } },
        awayTeam: { select: { id: true, name: true, shortName: true, logo: true } },
        league: { select: { id: true, name: true } },
      },
      orderBy: { matchDate: 'asc' },
    }),
    prisma.akcFixture.findMany({
      where: {
        OR: [
          { matchDate: { gte: from, lte: to } },
          { umugandaDayId: umugandaDay.id },
        ],
      },
      include: {
        homeTeam: { include: { school: { select: { id: true, name: true, shortName: true } } } },
        awayTeam: { include: { school: { select: { id: true, name: true, shortName: true } } } },
      },
      orderBy: { matchDate: 'asc' },
    }),
  ]);

  // A fixture belongs to this day if it still sits on it, or if it was moved
  // OFF it (umugandaDayId is the paper trail) — both matter to an admin.
  const onDay = (f: any) =>
    f.umugandaDayId === umugandaDay.id || kigaliDayKey(f.matchDate) === key;

  return {
    fixtures: fixtures.filter(onDay),
    akcFixtures: akcFixtures.filter(onDay).map(withAkcTeamNames),
  };
};

/**
 * Flag (or unflag) a fixture against the Umuganda calendar after its date changed.
 *
 * Deliberately conservative:
 *   - never touches a match an administrator has already ruled on
 *     (`umugandaDecision` set) — their decision is final;
 *   - never touches a match that is LIVE/ONGOING or COMPLETED;
 *   - never cancels anything. The worst it does is mark UMUGANDA_CONFLICT so the
 *     admin is asked the question.
 *
 * `kind` is 'LEAGUE' or 'AMASHURI'.
 */
const UNTOUCHABLE = ['LIVE', 'ONGOING', 'COMPLETED', 'CANCELLED'];

const syncFixtureConflict = async (kind: string, fixture: any) => {
  const delegate = kind === 'AMASHURI' ? prisma.akcFixture : prisma.fixture;
  const conflict = await detectConflict(fixture.matchDate);

  if (fixture.umugandaDecision) return { conflict, fixture, changed: false };
  if (UNTOUCHABLE.includes(fixture.status)) return { conflict, fixture, changed: false };

  if (conflict) {
    if (fixture.umugandaDayId === conflict.umugandaDay.id && fixture.status === 'UMUGANDA_CONFLICT') {
      return { conflict, fixture, changed: false };
    }
    const updated = await delegate.update({
      where: { id: fixture.id },
      data: { umugandaDayId: conflict.umugandaDay.id, status: 'UMUGANDA_CONFLICT' },
    });
    return { conflict, fixture: updated, changed: true };
  }

  // Moved clear of Umuganda without a formal decision — drop the stale flag.
  if (fixture.umugandaDayId && fixture.status === 'UMUGANDA_CONFLICT') {
    const updated = await delegate.update({
      where: { id: fixture.id },
      data: { umugandaDayId: null, status: 'SCHEDULED' },
    });
    return { conflict: null, fixture: updated, changed: true };
  }

  return { conflict: null, fixture, changed: false };
};

/**
 * Re-check fixtures that already sit on an Umuganda day.
 *
 * Generating a month's date does not, by itself, ask anything of the matches
 * already booked on it — those fixtures were saved before the date existed, so
 * nothing ever ran the conflict check on them. Without this pass a match
 * scheduled months in advance stays SCHEDULED forever and never reaches an
 * administrator's conflicts list.
 *
 * Delegates every decision to syncFixtureConflict, so the same guarantees hold:
 * an administrator's ruling is final, live and finished matches are left alone,
 * and nothing is ever cancelled.
 */
const rescanFixtures = async (days: any[]) => {
  let checked = 0;
  let flagged = 0;

  for (const day of days || []) {
    const { fixtures, akcFixtures } = await getAffectedFixtures(day);
    const families: any[] = [['LEAGUE', fixtures], ['AMASHURI', akcFixtures]];

    for (const [kind, list] of families) {
      for (const fixture of list) {
        checked += 1;
        const { changed } = await syncFixtureConflict(kind, fixture);
        if (changed) flagged += 1;
      }
    }
  }

  return { checked, flagged };
};

/**
 * The monthly preparation of §6, in one call: make sure the upcoming dates
 * exist, then reconcile the fixtures sitting on them. Used at boot and by the
 * admin "regenerate" action so both take exactly the same path.
 */
const prepareCalendar = async (count = DEFAULT_MONTHS_AHEAD, from = new Date()) => {
  const created = await ensureUpcomingMonths(count, from);
  const horizon = new Date(from.getTime());
  horizon.setUTCMonth(horizon.getUTCMonth() + count + 1);
  const days = await getEffectiveDays(new Date(from.getTime() - 86400000), horizon);
  const rescan = await rescanFixtures(days);
  return { created, ...rescan };
};

module.exports = {
  DEFAULT_MONTHS_AHEAD,
  ensureUpcomingMonths,
  getEffectiveDays,
  getNextDay,
  detectConflict,
  raiseNotice,
  getPublishedNotices,
  getAffectedFixtures,
  syncFixtureConflict,
  withAkcTeamNames,
  rescanFixtures,
  prepareCalendar,
};
